version: "3.7"

services:
  python:
    build: .
    init: true
    ports:
      - '8000:8000'
    restart: always
    environment:
      TZ: Australia/Perth
      SELPI_HISTORY_DB_PATH: /data/selpi-history.db
    volumes:
      - ./data:/data
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
