import struct
from memory import convert
from memory import Range

def create(arg):
    if type(arg) is str:
        return Variable(arg, MAP[arg][ADDRESS])
    if type(arg) is int:
        return Variable(address_to_name(arg), arg)
    raise NotImplementedError("Unable to create Variable from %s" % type(arg))

def address_to_name(address):
    for name in MAP.keys():
        if MAP[name][ADDRESS] == address:
            return name
    return 'Unknown'

ADDRESS = 'address'
TYPE = 'type'
DESCRIPTION = 'description'
UNITS = 'units'
CONVERSION = 'conversion'
FORMAT = 'format'
WORDS = 'words'

MAP = {
    "CommonScaleForAcVolts": {
        ADDRESS: 41000,
        TYPE: "ushort",
    },
    "CommonScaleForAcCurrent": {
        ADDRESS: 41001,
        TYPE: "ushort",
    },
    "CommonScaleForDcVolts": {
        ADDRESS: 41002,
        TYPE: "ushort",
    },
    "CommonScaleForDcCurrent": {
        ADDRESS: 41003,
        TYPE: "ushort",
    },
    "CommonScaleForTemperature": {
        ADDRESS: 41004,
        TYPE: "ushort",
    },
    "CommonScaleForInternalVoltages": {
        ADDRESS: 41005,
        TYPE: "ushort",
    },
    "TotalKacokWhTotalAcc": {
        DESCRIPTION: 'AC Lifetime Solar Energy',
        ADDRESS: 41519,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "CombinedKacoAcPowerHiRes": {
        DESCRIPTION: 'AC Solar Power',
        ADDRESS: 41896,
        TYPE: "uint",
        UNITS: "W",
        CONVERSION: "ac_w",
    },
    "LoadAcPower": {
        DESCRIPTION: 'AC Load Power',
        ADDRESS: 41107,
        TYPE: "uint",
        UNITS: "W",
        CONVERSION: "ac_w",
    },
    "ACLoadkWhTotalAcc": {
        DESCRIPTION: 'AC Lifetime Load Energy',
        ADDRESS: 41438,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "BatteryVolts": {
        DESCRIPTION: 'Battery Volts',
        ADDRESS: 41052,
        TYPE: "ushort",
        UNITS: "V",
        CONVERSION: "dc_v",
    },
    "DCBatteryPower": {
        DESCRIPTION: 'Battery Power',
        ADDRESS: 41007,
        TYPE: "int",
        UNITS: "W",
        CONVERSION: "dc_w",
    },
    "Shunt1Power": {
        DESCRIPTION: 'Shunt 1 Power',
        ADDRESS: 0xa088,
        TYPE: "short",
        UNITS: "W",
        CONVERSION: "dc_w",
    },
    "Shunt2Power": {
        DESCRIPTION: 'Shunt 2 Power',
        ADDRESS: 0xa089,
        TYPE: "short",
        UNITS: "W",
        CONVERSION: "dc_w",
    },
    "Shunt1Name": {
        DESCRIPTION: 'Shunt 1 Name',
        ADDRESS: 0xc109,
        TYPE: "short",
        UNITS: "",
        CONVERSION: "shunt_name",
    },
    "Shunt2Name": {
        DESCRIPTION: 'Shunt 2 Name',
        ADDRESS: 0xc10a,
        TYPE: "short",
        UNITS: "",
        CONVERSION: "shunt_name",
    },
     "Heatsink1Temp": {
        DESCRIPTION: "Heatsink 1 Temperature",
        ADDRESS: 41015,
        TYPE: "ushort",
        UNITS: "°C",
        CONVERSION: "temperature",
    },
     "Heatsink2Temp": {
        DESCRIPTION: "Heatsink 2 Temperature",
        ADDRESS: 41016,
        TYPE: "ushort",
        UNITS: "°C",
        CONVERSION: "temperature",
    },
     "ControlBoardTemp": {
        DESCRIPTION: "Control Board Temp",
        ADDRESS: 41019,
        TYPE: "ushort",
        UNITS: "°C",
        CONVERSION: "temperature",
    },
    "BatteryTemperature": {
        DESCRIPTION: "Battery Temperature",
        ADDRESS: 41020,
        TYPE: "ushort",
        UNITS: "°C",
        CONVERSION: "temperature",
    },
     "TransformerTemp": {
        DESCRIPTION: "Transformer Temperature",
        ADDRESS: 41021,
        TYPE: "ushort",
        UNITS: "°C",
        CONVERSION: "temperature",
    },
     "InletTemp": {
        DESCRIPTION: "Inlet Temperature",
        ADDRESS: 41022,
        TYPE: "ushort",
        UNITS: "°C",
        CONVERSION: "temperature",
    },
     "FanSpeed": {
        DESCRIPTION: "Fan Speed",
        ADDRESS: 41026,
        TYPE: "ushort",
        UNITS: "RPM",
    },
    "DCVolts": {
        DESCRIPTION: "DC Volts",
        ADDRESS: 41006,
        TYPE: "ushort",
        UNITS: "V",
        CONVERSION: "dc_v",
    },
    "VersionNumber": {
        DESCRIPTION: "Software Version",
        ADDRESS: 41010,
        TYPE: "ushort",
        UNITS: "",
    },
    "BuildDate1": {
        DESCRIPTION: "Build Date",
        ADDRESS: 41011,
        TYPE: "ushort",
        UNITS: "BCD",
    },
    "BuildDate2": {
        DESCRIPTION: "Build Date",
        ADDRESS: 41012,
        TYPE: "ushort",
        UNITS: "BCD",
    },
    "BuildTime": {
        DESCRIPTION: "Build Time",
        ADDRESS: 41013,
        TYPE: "ushort",
        UNITS: "BCD",
    },
    "GridFirmwareVersion": {
        DESCRIPTION: "Grid Software Version",
        ADDRESS: 41014,
        TYPE: "ushort",
        UNITS: "",
    },
    "InverterRunHrsTotalAcc": {
        DESCRIPTION: "Inverter Run Hours Total",
        ADDRESS: 41023,
        TYPE: "uint",
        UNITS: "Hours",
        CONVERSION: "minutes_to_hours",
    },
    "FanLife": {
        DESCRIPTION: "Fan Life",
        ADDRESS: 41025,
        TYPE: "ushort",
        UNITS: "%",
        CONVERSION: "percent_ushort",
    },
    "CapacitorLifeConsumedPM1": {
        DESCRIPTION: "Capacitor Life Consumed PM1",
        ADDRESS: 41027,
        TYPE: "ushort",
        UNITS: "%",
        CONVERSION: "percent_ushort",
    },
    "CapacitorLifeConsumedPM2": {
        DESCRIPTION: "Capacitor Life Consumed PM2",
        ADDRESS: 41028,
        TYPE: "ushort",
        UNITS: "%",
        CONVERSION: "percent_ushort",
    },
    "ChargeStatus": {
        DESCRIPTION: "Charge Status",
        ADDRESS: 41029,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "BatteryMidPoint": {
        DESCRIPTION: "Battery Mid Point",
        ADDRESS: 41030,
        TYPE: "ushort",
        UNITS: "V",
        CONVERSION: "dc_v",
    },
    "DaysSinceEqualise": {
        DESCRIPTION: "Days Since Equalise",
        ADDRESS: 41031,
        TYPE: "ushort",
        UNITS: "Days",
    },
    "DaysToEqualise": {
        DESCRIPTION: "Days to Equalise",
        ADDRESS: 41032,
        TYPE: "ushort",
        UNITS: "Days",
    },
    "ChargeIndex": {
        DESCRIPTION: "Charge Index",
        ADDRESS: 41033,
        TYPE: "ushort",
        UNITS: "",
    },
    "BatteryCableLoss": {
        DESCRIPTION: "Battery Cable Loss",
        ADDRESS: 41034,
        TYPE: "ushort",
        UNITS: "W",
    },
    "DigitalOutStatus1": {
        DESCRIPTION: "Digital Out Status 1",
        ADDRESS: 41035,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "DigitalOutStatus2": {
        DESCRIPTION: "Digital Out Status 2",
        ADDRESS: 41036,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "DigitalOutStatus3": {
        DESCRIPTION: "Digital Out Status 3",
        ADDRESS: 41037,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "DigitalOutStatus4": {
        DESCRIPTION: "Digital Out Status 4",
        ADDRESS: 41038,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "DigitalOutStatus5": {
        DESCRIPTION: "Digital Out Status 5",
        ADDRESS: 41039,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "DigitalOutStatus6": {
        DESCRIPTION: "Digital Out Status 6",
        ADDRESS: 41040,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "DigitalOutStatus7": {
        DESCRIPTION: "Digital Out Status 7",
        ADDRESS: 41041,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "DigitalInStatus1": {
        DESCRIPTION: "Digital In Status 1",
        ADDRESS: 41042,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "DigitalInStatus2": {
        DESCRIPTION: "Digital In Status 2",
        ADDRESS: 41043,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "DigitalInStatus3": {
        DESCRIPTION: "Digital In Status 3",
        ADDRESS: 41044,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "DigitalInStatus4": {
        DESCRIPTION: "Digital In Status 4",
        ADDRESS: 41045,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "GeneralPurpose1": {
        DESCRIPTION: "General Purpose 1",
        ADDRESS: 41046,
        TYPE: "ushort",
        UNITS: "V",
        CONVERSION: "dc_v",
    },
    "GeneralPurpose2": {
        DESCRIPTION: "General Purpose 2",
        ADDRESS: 41047,
        TYPE: "ushort",
        UNITS: "V",
        CONVERSION: "dc_v",
    },
    "ACInverterPower": {
        DESCRIPTION: "AC Inverter Power",
        ADDRESS: 41048,
        TYPE: "int",
        UNITS: "W",
        CONVERSION: "ac_w",
    },
    "InverterReactivePower": {
        DESCRIPTION: "Inverter Reactive Power",
        ADDRESS: 41050,
        TYPE: "short",
        UNITS: "W",
    },
    "BatterySenseVolts": {
        DESCRIPTION: "Battery Sense Volts",
        ADDRESS: 41051,
        TYPE: "ushort",
        UNITS: "V",
        CONVERSION: "dc_v",
    },
    "UnitModelNumber": {
        DESCRIPTION: "Unit Model Number",
        ADDRESS: 41053,
        TYPE: "ushort",
        UNITS: "",
    },
    "UnitSerialNumber": {
        DESCRIPTION: "Unit Serial Number",
        ADDRESS: 41054,
        TYPE: "uint",
        UNITS: "",
    },
    "UnitRevNumber": {
        DESCRIPTION: "Unit Rev Number",
        ADDRESS: 41056,
        TYPE: "ushort",
        UNITS: "",
    },
    "UnitModStatus": {
        DESCRIPTION: "Unit Mod Status",
        ADDRESS: 41057,
        TYPE: "ushort",
        UNITS: "",
    },
    "ControlPCASerialNumber": {
        DESCRIPTION: "Control PCA Serial Number",
        ADDRESS: 41058,
        TYPE: "uint",
        UNITS: "",
    },
    "ControlPCARevNumber": {
        DESCRIPTION: "Control PCA Rev Number",
        ADDRESS: 41060,
        TYPE: "ushort",
        UNITS: "",
    },
    "ControlPCAModStatus": {
        DESCRIPTION: "Control PCA Mod Status",
        ADDRESS: 41061,
        TYPE: "ushort",
        UNITS: "",
    },
    "PM1SerialNumber": {
        DESCRIPTION: "PM1 Serial Number",
        ADDRESS: 41062,
        TYPE: "uint",
        UNITS: "",
    },
    "PM1RevNumber": {
        DESCRIPTION: "PM1 Rev Number",
        ADDRESS: 41064,
        TYPE: "ushort",
        UNITS: "",
    },
    "PM1ModStatus": {
        DESCRIPTION: "PM1 Mod Status",
        ADDRESS: 41065,
        TYPE: "ushort",
        UNITS: "",
    },
    "PM2SerialNumber": {
        DESCRIPTION: "PM2 Serial Number",
        ADDRESS: 41066,
        TYPE: "uint",
        UNITS: "",
    },
    "PM2RevNumber": {
        DESCRIPTION: "PM2 Rev Number",
        ADDRESS: 41068,
        TYPE: "ushort",
        UNITS: "",
    },
    "PM2ModStatus": {
        DESCRIPTION: "PM2 Mod Status",
        ADDRESS: 41069,
        TYPE: "ushort",
        UNITS: "",
    },
    "ActiveScheduler": {
        DESCRIPTION: "Active Schedule",
        ADDRESS: 41072,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "AcInputCapacity": {
        DESCRIPTION: "Input Power Limit",
        ADDRESS: 41073,
        TYPE: "ushort",
        UNITS: "W",
    },
    "AcExportCapacity": {
        DESCRIPTION: "Export Power Limit",
        ADDRESS: 41074,
        TYPE: "ushort",
        UNITS: "W",
    },
    "InvDcChargeCapacity": {
        DESCRIPTION: "Charge Power Limit",
        ADDRESS: 41075,
        TYPE: "ushort",
        UNITS: "W",
    },
    "InvDcSupportCapacity": {
        DESCRIPTION: "Support Power Limit",
        ADDRESS: 41076,
        TYPE: "ushort",
        UNITS: "W",
    },
    "ChargerStatus": {
        DESCRIPTION: "Charger Status",
        ADDRESS: 41077,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "InverterLockoutActive": {
        DESCRIPTION: "Inverter Lockout Active",
        ADDRESS: 41078,
        TYPE: "ushort",
        UNITS: "Bool",
    },
    "AcInputLockoutActive": {
        DESCRIPTION: "AC Input Lockout Active",
        ADDRESS: 41079,
        TYPE: "ushort",
        UNITS: "Bool",
    },
    "ExportOnDemandTarget": {
        DESCRIPTION: "Export On Demand Target",
        ADDRESS: 41080,
        TYPE: "ushort",
        UNITS: "W",
    },
    "SoCRecoveryIsActive": {
        DESCRIPTION: "SoC Recovery Active",
        ADDRESS: 41081,
        TYPE: "ushort",
        UNITS: "Bool",
    },
    "ChargeStatusForNow": {
        DESCRIPTION: "Charge Status",
        ADDRESS: 41084,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "AcOutStatus": {
        DESCRIPTION: "AC Out Status",
        ADDRESS: 41085,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "AcSourceStatus": {
        DESCRIPTION: "AC Source Status",
        ADDRESS: 41088,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "DCCurrent": {
        DESCRIPTION: "DC Current",
        ADDRESS: 41091,
        TYPE: "short",
        UNITS: "A",
        CONVERSION: "dc_current",
    },
    "DCBatteryCurrent": {
        DESCRIPTION: "DC Battery Current",
        ADDRESS: 41092,
        TYPE: "int",
        UNITS: "A",
        CONVERSION: "dc_current",
    },
    "Shunt1Amps": {
        DESCRIPTION: "Shunt 1 Amps",
        ADDRESS: 41094,
        TYPE: "short",
        UNITS: "A",
        CONVERSION: "dc_current",
    },
    "Shunt2Amps": {
        DESCRIPTION: "Shunt 2 Amps",
        ADDRESS: 41095,
        TYPE: "short",
        UNITS: "A",
        CONVERSION: "dc_current",
    },
    "ACGeneratorPower": {
        DESCRIPTION: "AC Generator Power",
        ADDRESS: 41098,
        TYPE: "short",
        UNITS: "W",
        CONVERSION: "ac_w_ushort",
    },
    "ACGeneratorPower5minAvg": {
        DESCRIPTION: "AC Generator Power 5min Avg",
        ADDRESS: 41099,
        TYPE: "short",
        UNITS: "W",
        CONVERSION: "ac_w_ushort",
    },
    "ACGeneratorRmsAmps": {
        DESCRIPTION: "AC Generator RMS Amps",
        ADDRESS: 41100,
        TYPE: "short",
        UNITS: "A",
        CONVERSION: "dc_current",
    },
    "InputACHz": {
        DESCRIPTION: "Input AC Frequency",
        ADDRESS: 41101,
        TYPE: "ushort",
        UNITS: "Hz",
        CONVERSION: "centi_hz",
    },
    "MaxAvailableInputkW": {
        DESCRIPTION: "Max Available Input",
        ADDRESS: 41102,
        TYPE: "int",
        UNITS: "W",
        CONVERSION: "ac_w",
    },
    "ACInverterRmsVolts": {
        DESCRIPTION: "AC Inverter RMS Volts",
        ADDRESS: 41104,
        TYPE: "ushort",
        UNITS: "V",
        CONVERSION: "ac_v",
    },
    "ACInverterRmsAmps": {
        DESCRIPTION: "AC Inverter RMS Amps",
        ADDRESS: 41105,
        TYPE: "short",
        UNITS: "A",
        CONVERSION: "dc_current",
    },
    "InvFreq": {
        DESCRIPTION: "Inverter Frequency",
        ADDRESS: 41106,
        TYPE: "ushort",
        UNITS: "Hz",
        CONVERSION: "centi_hz",
    },
    "ACGeneratorRmsVolts": {
        DESCRIPTION: "AC Generator RMS Volts",
        ADDRESS: 41109,
        TYPE: "ushort",
        UNITS: "V",
        CONVERSION: "ac_v",
    },
    "BattLoad5Min": {
        DESCRIPTION: "5 Min Battery Load",
        ADDRESS: 41111,
        TYPE: "int",
        UNITS: "W",
        CONVERSION: "dc_w",
    },
    "BattLoad15Min": {
        DESCRIPTION: "15 Min Battery Load",
        ADDRESS: 41113,
        TYPE: "int",
        UNITS: "W",
        CONVERSION: "dc_w",
    },
    "NowKaco1AcPower": {
        DESCRIPTION: "Kaco 1 AC Power",
        ADDRESS: 41116,
        TYPE: "ushort",
        UNITS: "W",
        CONVERSION: "ac_w_ushort",
    },
    "NowKaco2AcPower": {
        DESCRIPTION: "Kaco 2 AC Power",
        ADDRESS: 41117,
        TYPE: "ushort",
        UNITS: "W",
        CONVERSION: "ac_w_ushort",
    },
    "NowKaco3AcPower": {
        DESCRIPTION: "Kaco 3 AC Power",
        ADDRESS: 41118,
        TYPE: "ushort",
        UNITS: "W",
        CONVERSION: "ac_w_ushort",
    },
    "NowKaco4AcPower": {
        DESCRIPTION: "Kaco 4 AC Power",
        ADDRESS: 41119,
        TYPE: "ushort",
        UNITS: "W",
        CONVERSION: "ac_w_ushort",
    },
    "NowKaco5AcPower": {
        DESCRIPTION: "Kaco 5 AC Power",
        ADDRESS: 41120,
        TYPE: "ushort",
        UNITS: "W",
        CONVERSION: "ac_w_ushort",
    },
    "AcCapacitorPercentage": {
        DESCRIPTION: "AC Capacitor Life",
        ADDRESS: 41133,
        TYPE: "ushort",
        UNITS: "%",
        CONVERSION: "percent_ushort",
    },
    "LoadVoltsHighFrequencyRipple": {
        DESCRIPTION: "Load Volts High Frequency Ripple",
        ADDRESS: 41134,
        TYPE: "ushort",
        UNITS: "V",
        CONVERSION: "ac_v",
    },
    "PercentageSolarOutput": {
        DESCRIPTION: "Solar Output Percentage",
        ADDRESS: 41121,
        TYPE: "ushort",
        UNITS: "%"
    },

    "BattInToday": {
        DESCRIPTION: "Battery In Energy Today",
        ADDRESS: 41176,
        TYPE: "uint",
        UNITS: "wh",
        CONVERSION: "dc_wh",
    },
    "BattOutToday": {
        DESCRIPTION: "Battery Out Energy Today",
        ADDRESS: 41178,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "BattNetToday": {
        DESCRIPTION: "Battery Net Today",
        ADDRESS: 41178,
        TYPE: "uint",
        UNITS: "wh",
        CONVERSION: "dc_wh",
    },
    "BattInYesterday": {
        DESCRIPTION: "Battery In Energy Yesterday",
        ADDRESS: 41329,
        TYPE: "uint",
        UNITS: "wh",
        CONVERSION: "dc_wh",
    },
    "BattOutYesterday": {
        DESCRIPTION: "Battery Out Energy Yesterday",
        ADDRESS: 41356,
        TYPE: "uint",
        UNITS: "wh",
        CONVERSION: "dc_wh",
    },
    "BattSocPercent": {
        DESCRIPTION: "Battery State of Charge",
        ADDRESS: 41089,
        TYPE: "ushort",
        UNITS: "%",
        CONVERSION: "percent",
    },
    "LoadAccumulatedToday": {
        DESCRIPTION: "Load Accumulated Today",
        ADDRESS: 41196,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACInputToday": {
        DESCRIPTION: "AC Accumulated Input Today",
        ADDRESS: 41151,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACInputYesterday": {
        DESCRIPTION: "AC Accumulated Input Yesterday",
        ADDRESS: 41440,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "DaysToRecharge": {
        DESCRIPTION: "Days to Recharge",
        ADDRESS: 41070,
        TYPE: "ushort",
        UNITS: "Days"
    },
    "FloatHours": {
        DESCRIPTION: "Float hours",
        ADDRESS: 41148,
        TYPE: "ushort",
        UNITS: "Hours"
    },
    "absorb": {
        DESCRIPTION: "Absorb",
        ADDRESS: 41217,
        TYPE: "ushort",
        UNITS: "Bool",
    },
    "bulk": {
        DESCRIPTION: "Bulk",
        ADDRESS: 41218,
        TYPE: "ushort",
        UNITS: "Bool",
    },
    "float": {
        DESCRIPTION: "Float",
        ADDRESS: 41220,
        TYPE: "ushort",
        UNITS: "Bool",
    },
    "GeneratorStartReason": {
        DESCRIPTION: "Generator Start Reason",
        ADDRESS: 41198,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "GeneratorRunningReason": {
        DESCRIPTION: "Generator Running Reason",
        ADDRESS: 41087,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "GeneratorStatus": {
        DESCRIPTION: "Generator Status",
        ADDRESS: 41110,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "GeneratorRed": {
        DESCRIPTION: "Generator Alarm",
        ADDRESS: 41225,
        TYPE: "ushort",
        UNITS: "Bool",
    },
    "GeneratorBtnPressPort1": {
        DESCRIPTION: "Generator Button Press Port 1",
        ADDRESS: 41522,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "GeneratorBtnStatusPort1": {
        DESCRIPTION: "Generator Button Status Port 1",
        ADDRESS: 41236,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "GeneratorBtnPressAllowed": {
        DESCRIPTION: "Generator Button Press Allowed",
        ADDRESS: 41242,
        TYPE: "ushort",
        UNITS: "Bool",
    },
    "OverTempRed": {
        DESCRIPTION: "Over Temp Alarm",
        ADDRESS: 41229,
        TYPE: "ushort",
        UNITS: "Bool",
    },
    "ServiceRequiredRed": {
        DESCRIPTION: "Service Required Alarm",
        ADDRESS: 41231,
        TYPE: "ushort",
        UNITS: "Bool",
    },
    "ShutdownRed": {
        DESCRIPTION: "Shutdown Alarm",
        ADDRESS: 41233,
        TYPE: "ushort",
        UNITS: "Bool",
    },
    "StringInverterSupport": {
        DESCRIPTION: "String Inverter Support",
        ADDRESS: 40981,
        TYPE: "ushort",
        UNITS: "Text",
    },
    # --- DC History ---
    "DCkWhIn": {
        DESCRIPTION: "DC Energy In (History)",
        ADDRESS: 41255,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "DCkWhOut": {
        DESCRIPTION: "DC Energy Out (History)",
        ADDRESS: 41257,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "DCkWhNet": {
        DESCRIPTION: "DC Energy Net (History)",
        ADDRESS: 41259,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "InverterDCkWhPreviousAcc": {
        DESCRIPTION: "Inverter DC Previous",
        ADDRESS: 41264,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "InverterDCkWh7DayAcc": {
        DESCRIPTION: "Inverter DC 7 Day",
        ADDRESS: 41265,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "InverterDCkWh7DayAccAvg": {
        DESCRIPTION: "Inverter DC 7 Day Avg",
        ADDRESS: 41267,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "InverterDCkWh30DayAcc": {
        DESCRIPTION: "Inverter DC 30 Day",
        ADDRESS: 41268,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "InverterDCkWh30DayAccAvg": {
        DESCRIPTION: "Inverter DC 30 Day Avg",
        ADDRESS: 41270,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "InverterDCkWh365DayAcc": {
        DESCRIPTION: "Inverter DC 365 Day",
        ADDRESS: 41271,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "InverterDCkWh365DayAccAvg": {
        DESCRIPTION: "Inverter DC 365 Day Avg",
        ADDRESS: 41273,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "InverterDCkWhYearAcc": {
        DESCRIPTION: "Inverter DC Year",
        ADDRESS: 41274,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "InverterDCkWhYearAccAvg": {
        DESCRIPTION: "Inverter DC Year Avg",
        ADDRESS: 41276,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "InverterDCkWhResetableAcc": {
        DESCRIPTION: "Inverter DC Resetable",
        ADDRESS: 41277,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "InverterDCkWhResetableAccAvg": {
        DESCRIPTION: "Inverter DC Resetable Avg",
        ADDRESS: 41279,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "InverterDCkWhTotalAcc": {
        DESCRIPTION: "Inverter DC Total",
        ADDRESS: 41283,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "Shunt1kWhPreviousAcc": {
        DESCRIPTION: "Shunt 1 Previous",
        ADDRESS: 41285,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "Shunt1PeakPowerPrevious": {
        DESCRIPTION: "Shunt 1 Peak Power Previous",
        ADDRESS: 41286,
        TYPE: "ushort",
        UNITS: "W",
    },
    "Shunt1kWh7DayAcc": {
        DESCRIPTION: "Shunt 1 7 Day",
        ADDRESS: 41287,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "Shunt1kWh7DayAccAvg": {
        DESCRIPTION: "Shunt 1 7 Day Avg",
        ADDRESS: 41289,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "Shunt1kWh30DayAcc": {
        DESCRIPTION: "Shunt 1 30 Day",
        ADDRESS: 41290,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "Shunt1kWh30DayAccAvg": {
        DESCRIPTION: "Shunt 1 30 Day Avg",
        ADDRESS: 41292,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "Shunt1kWh365DayAcc": {
        DESCRIPTION: "Shunt 1 365 Day",
        ADDRESS: 41293,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "Shunt1kWh365DayAccAvg": {
        DESCRIPTION: "Shunt 1 365 Day Avg",
        ADDRESS: 41295,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "Shunt1kWhYearAcc": {
        DESCRIPTION: "Shunt 1 Year",
        ADDRESS: 41296,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "Shunt1kWhYearAccAvg": {
        DESCRIPTION: "Shunt 1 Year Avg",
        ADDRESS: 41298,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "Shunt1kWhResetableAcc": {
        DESCRIPTION: "Shunt 1 Resetable",
        ADDRESS: 41299,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "Shunt1kWhResetableAccAvg": {
        DESCRIPTION: "Shunt 1 Resetable Avg",
        ADDRESS: 41301,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "Shunt1kWhTotalAcc": {
        DESCRIPTION: "Shunt 1 Total",
        ADDRESS: 41305,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "Shunt2PeakPowerPrevious": {
        DESCRIPTION: "Shunt 2 Peak Power Previous",
        ADDRESS: 41307,
        TYPE: "ushort",
        UNITS: "W",
    },
    "Shunt2kWhPreviousAcc": {
        DESCRIPTION: "Shunt 2 Previous",
        ADDRESS: 41308,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "Shunt2kWh7DayAcc": {
        DESCRIPTION: "Shunt 2 7 Day",
        ADDRESS: 41309,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "Shunt2kWh7DayAccAvg": {
        DESCRIPTION: "Shunt 2 7 Day Avg",
        ADDRESS: 41311,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "Shunt2kWh30DayAcc": {
        DESCRIPTION: "Shunt 2 30 Day",
        ADDRESS: 41312,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "Shunt2kWh30DayAccAvg": {
        DESCRIPTION: "Shunt 2 30 Day Avg",
        ADDRESS: 41314,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "Shunt2kWh365DayAcc": {
        DESCRIPTION: "Shunt 2 365 Day",
        ADDRESS: 41315,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "Shunt2kWh365DayAccAvg": {
        DESCRIPTION: "Shunt 2 365 Day Avg",
        ADDRESS: 41317,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "Shunt2kWhYearAcc": {
        DESCRIPTION: "Shunt 2 Year",
        ADDRESS: 41318,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "Shunt2kWhYearAccAvg": {
        DESCRIPTION: "Shunt 2 Year Avg",
        ADDRESS: 41320,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "Shunt2kWhResetableAcc": {
        DESCRIPTION: "Shunt 2 Resetable",
        ADDRESS: 41321,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "Shunt2kWhResetableAccAvg": {
        DESCRIPTION: "Shunt 2 Resetable Avg",
        ADDRESS: 41323,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "Shunt2kWhTotalAcc": {
        DESCRIPTION: "Shunt 2 Total",
        ADDRESS: 41327,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "BattInkWhPreviousAcc": {
        DESCRIPTION: "Battery In Previous",
        ADDRESS: 41329,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "BattInkWh7DayAcc": {
        DESCRIPTION: "Battery In 7 Day",
        ADDRESS: 41331,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "BattInkWh7DayAccAvg": {
        DESCRIPTION: "Battery In 7 Day Avg",
        ADDRESS: 41333,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "BattInkWh30DayAcc": {
        DESCRIPTION: "Battery In 30 Day",
        ADDRESS: 41335,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "BattInkWh30DayAccAvg": {
        DESCRIPTION: "Battery In 30 Day Avg",
        ADDRESS: 41337,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "BattInkWh365DayAcc": {
        DESCRIPTION: "Battery In 365 Day",
        ADDRESS: 41339,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "BattInkWh365DayAccAvg": {
        DESCRIPTION: "Battery In 365 Day Avg",
        ADDRESS: 41341,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "BattInkWhYearAcc": {
        DESCRIPTION: "Battery In Year",
        ADDRESS: 41343,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "BattInkWhYearAccAvg": {
        DESCRIPTION: "Battery In Year Avg",
        ADDRESS: 41345,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "BattInkWhResetableAcc": {
        DESCRIPTION: "Battery In Resetable",
        ADDRESS: 41347,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "BattInkWhResetableAccAvg": {
        DESCRIPTION: "Battery In Resetable Avg",
        ADDRESS: 41349,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "BattInkWhTotalAcc": {
        DESCRIPTION: "Battery In Total",
        ADDRESS: 41354,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "BattOutkWhPreviousAcc": {
        DESCRIPTION: "Battery Out Previous",
        ADDRESS: 41356,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "BattOutkWh7DayAcc": {
        DESCRIPTION: "Battery Out 7 Day",
        ADDRESS: 41358,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "BattOutkWh7DayAccAvg": {
        DESCRIPTION: "Battery Out 7 Day Avg",
        ADDRESS: 41360,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "BattOutkWh30DayAcc": {
        DESCRIPTION: "Battery Out 30 Day",
        ADDRESS: 41362,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "BattOutkWh30DayAccAvg": {
        DESCRIPTION: "Battery Out 30 Day Avg",
        ADDRESS: 41364,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "BattOutkWh365DayAcc": {
        DESCRIPTION: "Battery Out 365 Day",
        ADDRESS: 41366,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "BattOutkWh365DayAccAvg": {
        DESCRIPTION: "Battery Out 365 Day Avg",
        ADDRESS: 41368,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "BattOutkWhYearAcc": {
        DESCRIPTION: "Battery Out Year",
        ADDRESS: 41370,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "BattOutkWhYearAccAvg": {
        DESCRIPTION: "Battery Out Year Avg",
        ADDRESS: 41372,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "BattOutkWhResetableAcc": {
        DESCRIPTION: "Battery Out Resetable",
        ADDRESS: 41374,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "BattOutkWhResetableAccAvg": {
        DESCRIPTION: "Battery Out Resetable Avg",
        ADDRESS: 41376,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "BattOutkWhTotalAcc": {
        DESCRIPTION: "Battery Out Total",
        ADDRESS: 41381,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "dc_wh",
    },
    "FloatHrsPreviousAcc": {
        DESCRIPTION: "Float Hours Previous",
        ADDRESS: 41383,
        TYPE: "ushort",
        UNITS: "Hours",
    },
    "FloatHrs7DayAcc": {
        DESCRIPTION: "Float Hours 7 Day",
        ADDRESS: 41384,
        TYPE: "ushort",
        UNITS: "Hours",
    },
    "FloatHrs7DayAccAvg": {
        DESCRIPTION: "Float Hours 7 Day Avg",
        ADDRESS: 41385,
        TYPE: "ushort",
        UNITS: "Hours",
    },
    "FloatHrs30DayAcc": {
        DESCRIPTION: "Float Hours 30 Day",
        ADDRESS: 41386,
        TYPE: "ushort",
        UNITS: "Hours",
    },
    "FloatHrs30DayAccAvg": {
        DESCRIPTION: "Float Hours 30 Day Avg",
        ADDRESS: 41387,
        TYPE: "ushort",
        UNITS: "Hours",
    },
    "FloatHrs365DayAcc": {
        DESCRIPTION: "Float Hours 365 Day",
        ADDRESS: 41388,
        TYPE: "uint",
        UNITS: "Hours",
    },
    "FloatHrs365DayAccAvg": {
        DESCRIPTION: "Float Hours 365 Day Avg",
        ADDRESS: 41390,
        TYPE: "ushort",
        UNITS: "Hours",
    },
    "FloatHrsYearAcc": {
        DESCRIPTION: "Float Hours Year",
        ADDRESS: 41391,
        TYPE: "uint",
        UNITS: "Hours",
    },
    "FloatHrsYearAccAvg": {
        DESCRIPTION: "Float Hours Year Avg",
        ADDRESS: 41393,
        TYPE: "ushort",
        UNITS: "Hours",
    },
    "TimeFloatAchievedPrevious": {
        DESCRIPTION: "Time Float Achieved Previous",
        ADDRESS: 41394,
        TYPE: "ushort",
        UNITS: "BCD",
    },
    # --- AC History ---
    "TotalKacokWhPreviousAcc": {
        DESCRIPTION: "Solar Previous",
        ADDRESS: 41418,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACLoadkWhPreviousAcc": {
        DESCRIPTION: "AC Load Previous",
        ADDRESS: 41419,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACLoadkWh7DayAcc": {
        DESCRIPTION: "AC Load 7 Day",
        ADDRESS: 41420,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACLoadkWh7DayAccAvg": {
        DESCRIPTION: "AC Load 7 Day Avg",
        ADDRESS: 41422,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACLoadkWh30DayAcc": {
        DESCRIPTION: "AC Load 30 Day",
        ADDRESS: 41423,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACLoadkWh30DayAccAvg": {
        DESCRIPTION: "AC Load 30 Day Avg",
        ADDRESS: 41425,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACLoadkWh365DayAcc": {
        DESCRIPTION: "AC Load 365 Day",
        ADDRESS: 41426,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACLoadkWh365DayAccAvg": {
        DESCRIPTION: "AC Load 365 Day Avg",
        ADDRESS: 41428,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACLoadkWhYearAcc": {
        DESCRIPTION: "AC Load Year",
        ADDRESS: 41429,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACLoadkWhYearAccAvg": {
        DESCRIPTION: "AC Load Year Avg",
        ADDRESS: 41431,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACLoadkWhResetableAcc": {
        DESCRIPTION: "AC Load Resetable",
        ADDRESS: 41432,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACLoadkWhResetableAccAvg": {
        DESCRIPTION: "AC Load Resetable Avg",
        ADDRESS: 41434,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACInputkWhPrevious": {
        DESCRIPTION: "AC Input Previous",
        ADDRESS: 41440,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACInputkWh7DayAcc": {
        DESCRIPTION: "AC Input 7 Day",
        ADDRESS: 41441,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACInputkWh7DayAccAvg": {
        DESCRIPTION: "AC Input 7 Day Avg",
        ADDRESS: 41443,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACInputkWh30DayAcc": {
        DESCRIPTION: "AC Input 30 Day",
        ADDRESS: 41444,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACInputkWh30DayAccAvg": {
        DESCRIPTION: "AC Input 30 Day Avg",
        ADDRESS: 41446,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACInputkWh365DayAcc": {
        DESCRIPTION: "AC Input 365 Day",
        ADDRESS: 41447,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACInputkWh365DayAccAvg": {
        DESCRIPTION: "AC Input 365 Day Avg",
        ADDRESS: 41449,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACInputkWhYearAcc": {
        DESCRIPTION: "AC Input Year",
        ADDRESS: 41450,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACInputkWhYearAccAvg": {
        DESCRIPTION: "AC Input Year Avg",
        ADDRESS: 41452,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACInputkWhResetableAcc": {
        DESCRIPTION: "AC Input Resetable",
        ADDRESS: 41453,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACInputkWhResetableAccAvg": {
        DESCRIPTION: "AC Input Resetable Avg",
        ADDRESS: 41455,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACInputHrsPreviousAcc": {
        DESCRIPTION: "AC Input Hours Previous",
        ADDRESS: 41461,
        TYPE: "ushort",
        UNITS: "Hours",
    },
    "ACInputHrs7DayAcc": {
        DESCRIPTION: "AC Input Hours 7 Day",
        ADDRESS: 41462,
        TYPE: "ushort",
        UNITS: "Hours",
    },
    "ACInputHrs7DayAccAvg": {
        DESCRIPTION: "AC Input Hours 7 Day Avg",
        ADDRESS: 41463,
        TYPE: "ushort",
        UNITS: "Hours",
    },
    "ACInputHrs30DayAcc": {
        DESCRIPTION: "AC Input Hours 30 Day",
        ADDRESS: 41464,
        TYPE: "ushort",
        UNITS: "Hours",
    },
    "ACInputHrs30DayAccAvg": {
        DESCRIPTION: "AC Input Hours 30 Day Avg",
        ADDRESS: 41465,
        TYPE: "ushort",
        UNITS: "Hours",
    },
    "ACInputHrs365DayAcc": {
        DESCRIPTION: "AC Input Hours 365 Day",
        ADDRESS: 41466,
        TYPE: "uint",
        UNITS: "Hours",
    },
    "ACInputHrs365DayAccAvg": {
        DESCRIPTION: "AC Input Hours 365 Day Avg",
        ADDRESS: 41468,
        TYPE: "ushort",
        UNITS: "Hours",
    },
    "ACInputHrsYearAcc": {
        DESCRIPTION: "AC Input Hours Year",
        ADDRESS: 41469,
        TYPE: "uint",
        UNITS: "Hours",
    },
    "ACInputHrsYearAccAvg": {
        DESCRIPTION: "AC Input Hours Year Avg",
        ADDRESS: 41471,
        TYPE: "ushort",
        UNITS: "Hours",
    },
    "ACInputHrsResetableAcc": {
        DESCRIPTION: "AC Input Hours Resetable",
        ADDRESS: 41472,
        TYPE: "uint",
        UNITS: "Hours",
    },
    "ACInputHrsResetableAccAvg": {
        DESCRIPTION: "AC Input Hours Resetable Avg",
        ADDRESS: 41474,
        TYPE: "ushort",
        UNITS: "Hours",
    },
    "ACInputHrsTotalAcc": {
        DESCRIPTION: "AC Input Hours Total",
        ADDRESS: 41478,
        TYPE: "uint",
        UNITS: "Hours",
    },
    "ACExportkWhPrevious": {
        DESCRIPTION: "AC Export Previous",
        ADDRESS: 41480,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACExportkWh7DayAcc": {
        DESCRIPTION: "AC Export 7 Day",
        ADDRESS: 41481,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACExportkWh7DayAccAvg": {
        DESCRIPTION: "AC Export 7 Day Avg",
        ADDRESS: 41483,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACExportkWh30DayAcc": {
        DESCRIPTION: "AC Export 30 Day",
        ADDRESS: 41484,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACExportkWh30DayAccAvg": {
        DESCRIPTION: "AC Export 30 Day Avg",
        ADDRESS: 41486,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACExportkWh365DayAcc": {
        DESCRIPTION: "AC Export 365 Day",
        ADDRESS: 41487,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACExportkWh365DayAccAvg": {
        DESCRIPTION: "AC Export 365 Day Avg",
        ADDRESS: 41489,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACExportkWhYearAcc": {
        DESCRIPTION: "AC Export Year",
        ADDRESS: 41490,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACExportkWhYearAccAvg": {
        DESCRIPTION: "AC Export Year Avg",
        ADDRESS: 41492,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACExportkWhResetableAcc": {
        DESCRIPTION: "AC Export Resetable",
        ADDRESS: 41493,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACExportkWhResetableAccAvg": {
        DESCRIPTION: "AC Export Resetable Avg",
        ADDRESS: 41495,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "ACExportkWhTotalAcc": {
        DESCRIPTION: "AC Export Total",
        ADDRESS: 41499,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "TotalKacokWh7DayAcc": {
        DESCRIPTION: "Solar 7 Day",
        ADDRESS: 41501,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "TotalKacokWh7DayAccAvg": {
        DESCRIPTION: "Solar 7 Day Avg",
        ADDRESS: 41503,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "TotalKacokWh30DayAcc": {
        DESCRIPTION: "Solar 30 Day",
        ADDRESS: 41504,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "TotalKacokWh30DayAccAvg": {
        DESCRIPTION: "Solar 30 Day Avg",
        ADDRESS: 41506,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "TotalKacokWh365DayAcc": {
        DESCRIPTION: "Solar 365 Day",
        ADDRESS: 41507,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "TotalKacokWh365DayAccAvg": {
        DESCRIPTION: "Solar 365 Day Avg",
        ADDRESS: 41509,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "TotalKacokWhYearAcc": {
        DESCRIPTION: "Solar Year",
        ADDRESS: 41510,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "TotalKacokWhYearAccAvg": {
        DESCRIPTION: "Solar Year Avg",
        ADDRESS: 41512,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "TotalKacokWhResetableAcc": {
        DESCRIPTION: "Solar Resetable",
        ADDRESS: 41513,
        TYPE: "uint",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    "TotalKacokWhResetableAccAvg": {
        DESCRIPTION: "Solar Resetable Avg",
        ADDRESS: 41515,
        TYPE: "ushort",
        UNITS: "Wh",
        CONVERSION: "ac_wh",
    },
    # --- Service Required Reasons (Attention Required) ---
    "ServiceRequiredReason0": {
        DESCRIPTION: "Service Required Reason 0",
        ADDRESS: 41533,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "ServiceRequiredReason1": {
        DESCRIPTION: "Service Required Reason 1",
        ADDRESS: 41534,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "ServiceRequiredReason2": {
        DESCRIPTION: "Service Required Reason 2",
        ADDRESS: 41535,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "ServiceRequiredReason3": {
        DESCRIPTION: "Service Required Reason 3",
        ADDRESS: 41536,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "ServiceRequiredReason4": {
        DESCRIPTION: "Service Required Reason 4",
        ADDRESS: 41537,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "ServiceRequiredReason5": {
        DESCRIPTION: "Service Required Reason 5",
        ADDRESS: 41538,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "ServiceRequiredReason6": {
        DESCRIPTION: "Service Required Reason 6",
        ADDRESS: 41539,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "ServiceRequiredReason7": {
        DESCRIPTION: "Service Required Reason 7",
        ADDRESS: 41540,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "ServiceRequiredReason8": {
        DESCRIPTION: "Service Required Reason 8",
        ADDRESS: 41541,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "ServiceRequiredReason9": {
        DESCRIPTION: "Service Required Reason 9",
        ADDRESS: 41542,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "ServiceRequiredReason10": {
        DESCRIPTION: "Service Required Reason 10",
        ADDRESS: 41543,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "ServiceRequiredReason11": {
        DESCRIPTION: "Service Required Reason 11",
        ADDRESS: 41544,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "ServiceRequiredReason12": {
        DESCRIPTION: "Service Required Reason 12",
        ADDRESS: 41545,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "ServiceRequiredReason13": {
        DESCRIPTION: "Service Required Reason 13",
        ADDRESS: 41546,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "ServiceRequiredReason14": {
        DESCRIPTION: "Service Required Reason 14",
        ADDRESS: 41547,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "ServiceRequiredReason15": {
        DESCRIPTION: "Service Required Reason 15",
        ADDRESS: 41548,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "ServiceRequiredReason16": {
        DESCRIPTION: "Service Required Reason 16",
        ADDRESS: 41549,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "ServiceRequiredReason17": {
        DESCRIPTION: "Service Required Reason 17",
        ADDRESS: 41550,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "ServiceRequiredReason18": {
        DESCRIPTION: "Service Required Reason 18",
        ADDRESS: 41551,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "ServiceRequiredReason19": {
        DESCRIPTION: "Service Required Reason 19",
        ADDRESS: 41552,
        TYPE: "ushort",
        UNITS: "Text",
    },
    "LoginHash": {
        ADDRESS: 0x1f0000,
        TYPE: ""
    },
    "LoginStatus": {
        ADDRESS: 0x1f0010,
        TYPE: "ushort"
    },
}

TYPES = {
    "ushort": {
        FORMAT: "<H",
        WORDS: 1,
    },
    "short": {
        FORMAT: "<h",
        WORDS: 1,
    },
    "uint": {
        FORMAT: "<I",
        WORDS: 2,
    },
    "int": {
        FORMAT: "<i",
        WORDS: 2,
    },
}

class Variable:
    def __init__(self, name: str, address: int, bytes: bytes=b'\x00\x00'):
        self.__name = name
        self.__address = address
        self.__bytes = bytes

    def get_name(self):
        return self.__name

    """
    Get the memory range for this variable
    """
    @property
    def range(self):
        return Range(self.__address, TYPES[self.get_type()][WORDS])

    def get_type(self):
        if not self.__name in MAP:
            return 'ushort'
        return MAP[self.__name][TYPE]

    """
    Set the internal bytes
    """
    @property
    def bytes(self):
        return self.__bytes

    @bytes.setter
    def bytes(self, bytes):
        self.__bytes = bytes

    """
    Get the converted value
    """
    def get_value(self, scales: dict):
        if not self.is_known():
            raise Exception("Can not convert value for unknown variable type")
        mem_info = MAP[self.__name]
        type_info = TYPES[self.get_type()]
        format = type_info["format"]
        unscaled = struct.unpack(format, self.__bytes)[0]
        if not CONVERSION in mem_info:
            return unscaled
        return convert(mem_info[CONVERSION], unscaled, scales)

    def is_known(self):
        return self.__name in MAP
