from muster import Muster
from memory import variable
from datetime import datetime




class Statistics():
    def __init__(self):
        self.__muster = Muster()
        self.__scale_variables = [
            variable.create('CommonScaleForAcVolts'),
            variable.create('CommonScaleForAcCurrent'),
            variable.create('CommonScaleForDcVolts'),
            variable.create('CommonScaleForDcCurrent'),
            variable.create('CommonScaleForTemperature'),
            variable.create('CommonScaleForInternalVoltages'),
        ]
        self.__variables = [
            variable.create('CombinedKacoAcPowerHiRes'),
            variable.create('LoadAcPower'),
            variable.create('ACLoadkWhTotalAcc'),
            variable.create('BatteryVolts'),
            variable.create('DCBatteryPower'),
            variable.create('Shunt1Name'),
            variable.create('Shunt1Power'),
            variable.create('Shunt2Name'),
            variable.create('Shunt2Power'),
            variable.create('Heatsink1Temp'),
            variable.create('Heatsink2Temp'),
            variable.create('ControlBoardTemp'),
            variable.create('BatteryTemperature'),
            variable.create('TransformerTemp'),
            variable.create('InletTemp'),
            variable.create('FanSpeed'),
            variable.create('BattOutToday'),
            variable.create('BattInToday'),
            variable.create('BattNetToday'),
            variable.create('BattInYesterday'),
            variable.create('BattOutYesterday'),
            variable.create('absorb'),
            variable.create('bulk'),
            variable.create('float'),
            variable.create('BattSocPercent'),
            variable.create('LoadAccumulatedToday'),
            variable.create('PercentageSolarOutput'),
            variable.create("GeneratorStartReason"),
            variable.create("GeneratorRunningReason"),
            variable.create("GeneratorStatus"),
            variable.create("ACInputToday"),
            variable.create("ACInputYesterday"),
            variable.create("FloatHours"),
            variable.create("GeneratorRed"),
            variable.create("OverTempRed"),
            variable.create("ServiceRequiredRed"),
            variable.create("ShutdownRed"),

            # --- Data View: Now sub-tab ---
            variable.create('AcOutStatus'),
            variable.create('AcSourceStatus'),
            variable.create('ChargeStatusForNow'),
            variable.create('InvFreq'),
            variable.create('DCCurrent'),
            variable.create('DCBatteryCurrent'),
            variable.create('Shunt1Amps'),
            variable.create('Shunt2Amps'),
            variable.create('ACGeneratorPower'),
            variable.create('ACGeneratorPower5minAvg'),
            variable.create('ACGeneratorRmsVolts'),
            variable.create('ACGeneratorRmsAmps'),
            variable.create('InputACHz'),
            variable.create('MaxAvailableInputkW'),
            variable.create('ACInverterRmsVolts'),
            variable.create('ACInverterRmsAmps'),
            variable.create('BattLoad5Min'),
            variable.create('BattLoad15Min'),
            variable.create('NowKaco1AcPower'),
            variable.create('NowKaco2AcPower'),
            variable.create('NowKaco3AcPower'),
            variable.create('NowKaco4AcPower'),
            variable.create('NowKaco5AcPower'),
            variable.create('ActiveScheduler'),
            variable.create('AcInputCapacity'),
            variable.create('AcExportCapacity'),
            variable.create('InvDcChargeCapacity'),
            variable.create('InvDcSupportCapacity'),
            variable.create('ChargerStatus'),
            variable.create('InverterLockoutActive'),
            variable.create('AcInputLockoutActive'),
            variable.create('ExportOnDemandTarget'),
            variable.create('SoCRecoveryIsActive'),

            # --- Data View: Technical Data sub-tab ---
            variable.create('DCVolts'),
            variable.create('BatteryMidPoint'),
            variable.create('DaysSinceEqualise'),
            variable.create('DaysToEqualise'),
            variable.create('DaysToRecharge'),
            variable.create('ChargeIndex'),
            variable.create('BatteryCableLoss'),
            variable.create('ACInverterPower'),
            variable.create('InverterReactivePower'),
            variable.create('BatterySenseVolts'),
            variable.create('UnitModelNumber'),
            variable.create('UnitSerialNumber'),
            variable.create('UnitRevNumber'),
            variable.create('UnitModStatus'),
            variable.create('VersionNumber'),
            variable.create('StringInverterSupport'),
            variable.create('GridFirmwareVersion'),
            variable.create('BuildDate1'),
            variable.create('BuildDate2'),
            variable.create('BuildTime'),
            variable.create('InverterRunHrsTotalAcc'),
            variable.create('ControlPCASerialNumber'),
            variable.create('ControlPCARevNumber'),
            variable.create('ControlPCAModStatus'),
            variable.create('PM1SerialNumber'),
            variable.create('PM1RevNumber'),
            variable.create('PM1ModStatus'),
            variable.create('PM2SerialNumber'),
            variable.create('PM2RevNumber'),
            variable.create('PM2ModStatus'),
            variable.create('FanLife'),
            variable.create('CapacitorLifeConsumedPM1'),
            variable.create('CapacitorLifeConsumedPM2'),
            variable.create('AcCapacitorPercentage'),
            variable.create('LoadVoltsHighFrequencyRipple'),
            variable.create('DigitalInStatus1'),
            variable.create('DigitalInStatus2'),
            variable.create('DigitalInStatus3'),
            variable.create('DigitalInStatus4'),
            variable.create('DigitalOutStatus1'),
            variable.create('DigitalOutStatus2'),
            variable.create('DigitalOutStatus3'),
            variable.create('DigitalOutStatus4'),
            variable.create('DigitalOutStatus5'),
            variable.create('DigitalOutStatus6'),
            variable.create('DigitalOutStatus7'),
            variable.create('GeneralPurpose1'),
            variable.create('GeneralPurpose2'),

            # --- Data View: DC History ---
            variable.create('InverterDCkWhPreviousAcc'),
            variable.create('InverterDCkWh7DayAcc'),
            variable.create('InverterDCkWh7DayAccAvg'),
            variable.create('InverterDCkWh30DayAcc'),
            variable.create('InverterDCkWh30DayAccAvg'),
            variable.create('InverterDCkWh365DayAcc'),
            variable.create('InverterDCkWh365DayAccAvg'),
            variable.create('InverterDCkWhYearAcc'),
            variable.create('InverterDCkWhYearAccAvg'),
            variable.create('InverterDCkWhResetableAcc'),
            variable.create('InverterDCkWhResetableAccAvg'),
            variable.create('InverterDCkWhTotalAcc'),
            variable.create('Shunt1kWhPreviousAcc'),
            variable.create('Shunt1PeakPowerPrevious'),
            variable.create('Shunt1kWh7DayAcc'),
            variable.create('Shunt1kWh7DayAccAvg'),
            variable.create('Shunt1kWh30DayAcc'),
            variable.create('Shunt1kWh30DayAccAvg'),
            variable.create('Shunt1kWh365DayAcc'),
            variable.create('Shunt1kWh365DayAccAvg'),
            variable.create('Shunt1kWhYearAcc'),
            variable.create('Shunt1kWhYearAccAvg'),
            variable.create('Shunt1kWhResetableAcc'),
            variable.create('Shunt1kWhResetableAccAvg'),
            variable.create('Shunt1kWhTotalAcc'),
            variable.create('Shunt2kWhPreviousAcc'),
            variable.create('Shunt2PeakPowerPrevious'),
            variable.create('Shunt2kWh7DayAcc'),
            variable.create('Shunt2kWh7DayAccAvg'),
            variable.create('Shunt2kWh30DayAcc'),
            variable.create('Shunt2kWh30DayAccAvg'),
            variable.create('Shunt2kWh365DayAcc'),
            variable.create('Shunt2kWh365DayAccAvg'),
            variable.create('Shunt2kWhYearAcc'),
            variable.create('Shunt2kWhYearAccAvg'),
            variable.create('Shunt2kWhResetableAcc'),
            variable.create('Shunt2kWhResetableAccAvg'),
            variable.create('Shunt2kWhTotalAcc'),
            variable.create('BattInkWhPreviousAcc'),
            variable.create('BattInkWh7DayAcc'),
            variable.create('BattInkWh7DayAccAvg'),
            variable.create('BattInkWh30DayAcc'),
            variable.create('BattInkWh30DayAccAvg'),
            variable.create('BattInkWh365DayAcc'),
            variable.create('BattInkWh365DayAccAvg'),
            variable.create('BattInkWhYearAcc'),
            variable.create('BattInkWhYearAccAvg'),
            variable.create('BattInkWhResetableAcc'),
            variable.create('BattInkWhResetableAccAvg'),
            variable.create('BattInkWhTotalAcc'),
            variable.create('BattOutkWhPreviousAcc'),
            variable.create('BattOutkWh7DayAcc'),
            variable.create('BattOutkWh7DayAccAvg'),
            variable.create('BattOutkWh30DayAcc'),
            variable.create('BattOutkWh30DayAccAvg'),
            variable.create('BattOutkWh365DayAcc'),
            variable.create('BattOutkWh365DayAccAvg'),
            variable.create('BattOutkWhYearAcc'),
            variable.create('BattOutkWhYearAccAvg'),
            variable.create('BattOutkWhResetableAcc'),
            variable.create('BattOutkWhResetableAccAvg'),
            variable.create('BattOutkWhTotalAcc'),
            variable.create('FloatHrsPreviousAcc'),
            variable.create('FloatHrs7DayAcc'),
            variable.create('FloatHrs7DayAccAvg'),
            variable.create('FloatHrs30DayAcc'),
            variable.create('FloatHrs30DayAccAvg'),
            variable.create('FloatHrs365DayAcc'),
            variable.create('FloatHrs365DayAccAvg'),
            variable.create('FloatHrsYearAcc'),
            variable.create('FloatHrsYearAccAvg'),
            variable.create('TimeFloatAchievedPrevious'),

            # --- Data View: AC History ---
            variable.create('TotalKacokWhPreviousAcc'),
            variable.create('ACLoadkWhPreviousAcc'),
            variable.create('ACLoadkWh7DayAcc'),
            variable.create('ACLoadkWh7DayAccAvg'),
            variable.create('ACLoadkWh30DayAcc'),
            variable.create('ACLoadkWh30DayAccAvg'),
            variable.create('ACLoadkWh365DayAcc'),
            variable.create('ACLoadkWh365DayAccAvg'),
            variable.create('ACLoadkWhYearAcc'),
            variable.create('ACLoadkWhYearAccAvg'),
            variable.create('ACLoadkWhResetableAcc'),
            variable.create('ACLoadkWhResetableAccAvg'),
            variable.create('ACInputkWhPrevious'),
            variable.create('ACInputkWh7DayAcc'),
            variable.create('ACInputkWh7DayAccAvg'),
            variable.create('ACInputkWh30DayAcc'),
            variable.create('ACInputkWh30DayAccAvg'),
            variable.create('ACInputkWh365DayAcc'),
            variable.create('ACInputkWh365DayAccAvg'),
            variable.create('ACInputkWhYearAcc'),
            variable.create('ACInputkWhYearAccAvg'),
            variable.create('ACInputkWhResetableAcc'),
            variable.create('ACInputkWhResetableAccAvg'),
            variable.create('ACInputHrsPreviousAcc'),
            variable.create('ACInputHrs7DayAcc'),
            variable.create('ACInputHrs7DayAccAvg'),
            variable.create('ACInputHrs30DayAcc'),
            variable.create('ACInputHrs30DayAccAvg'),
            variable.create('ACInputHrs365DayAcc'),
            variable.create('ACInputHrs365DayAccAvg'),
            variable.create('ACInputHrsYearAcc'),
            variable.create('ACInputHrsYearAccAvg'),
            variable.create('ACInputHrsResetableAcc'),
            variable.create('ACInputHrsResetableAccAvg'),
            variable.create('ACInputHrsTotalAcc'),
            variable.create('ACExportkWhPrevious'),
            variable.create('ACExportkWh7DayAcc'),
            variable.create('ACExportkWh7DayAccAvg'),
            variable.create('ACExportkWh30DayAcc'),
            variable.create('ACExportkWh30DayAccAvg'),
            variable.create('ACExportkWh365DayAcc'),
            variable.create('ACExportkWh365DayAccAvg'),
            variable.create('ACExportkWhYearAcc'),
            variable.create('ACExportkWhYearAccAvg'),
            variable.create('ACExportkWhResetableAcc'),
            variable.create('ACExportkWhResetableAccAvg'),
            variable.create('ACExportkWhTotalAcc'),
            variable.create('TotalKacokWh7DayAcc'),
            variable.create('TotalKacokWh7DayAccAvg'),
            variable.create('TotalKacokWh30DayAcc'),
            variable.create('TotalKacokWh30DayAccAvg'),
            variable.create('TotalKacokWh365DayAcc'),
            variable.create('TotalKacokWh365DayAccAvg'),
            variable.create('TotalKacokWhYearAcc'),
            variable.create('TotalKacokWhYearAccAvg'),
            variable.create('TotalKacokWhResetableAcc'),
            variable.create('TotalKacokWhResetableAccAvg'),

            # --- Service Required Reasons (Attention Required) ---
            variable.create('ServiceRequiredReason0'),
            variable.create('ServiceRequiredReason1'),
            variable.create('ServiceRequiredReason2'),
            variable.create('ServiceRequiredReason3'),
            variable.create('ServiceRequiredReason4'),
            variable.create('ServiceRequiredReason5'),
            variable.create('ServiceRequiredReason6'),
            variable.create('ServiceRequiredReason7'),
            variable.create('ServiceRequiredReason8'),
            variable.create('ServiceRequiredReason9'),
            variable.create('ServiceRequiredReason10'),
            variable.create('ServiceRequiredReason11'),
            variable.create('ServiceRequiredReason12'),
            variable.create('ServiceRequiredReason13'),
            variable.create('ServiceRequiredReason14'),
            variable.create('ServiceRequiredReason15'),
            variable.create('ServiceRequiredReason16'),
            variable.create('ServiceRequiredReason17'),
            variable.create('ServiceRequiredReason18'),
            variable.create('ServiceRequiredReason19'),
        ]
        self.__scales = None
        self.__duskTodayAC = -1
        self.__duskYesterdayAC = -1
        self.__duskDaysToRecharge = -1

    def __update(self, variables):
        # opportunistically request scales if they're missing during another
        # request
        if not self.__scales:
            variables = variables + self.__scale_variables

        self.__muster.update(variables)

    def get(self):
        self.__update(self.__variables)
        stats = []
        for var in self.__variables:
            stats.append({
                "description": variable.MAP[var.get_name()][variable.DESCRIPTION],
                "name": var.get_name(),
                "value": var.get_value(self.scales),
                "units": variable.MAP[var.get_name()][variable.UNITS],
            })
            if (datetime.now().hour == 16 and datetime.now().minute in [0, 1, 2]) or (datetime.now().hour > 16 and self.__duskTodayAC == -1):
                if self.__duskTodayAC != -1:
                    self.__duskYesterdayAC = self.__duskTodayAC
                self.__duskTodayAC = self.__variables[27].get_value(self.scales)
                self.__duskDaysToRecharge = self.__variables[29].get_value(self.scales)

        stats.append({
                "description": "AC Input Dusk Today",
                "name": "ACInputDuskToday",
                "value": self.__duskTodayAC,
                "units": "Wh",
        })

        stats.append({
            "description": "AC Input Dusk Yesterday",
            "name": "ACInputDuskYesterday",
            "value": self.__duskYesterdayAC,
            "units": "Wh",
        })

        stats.append({
            "description": "Dusk Days to Recharge",
            "name": "DuskDaysToRecharge",
            "value": self.__duskDaysToRecharge,
            "units": "Days",
        })

        return stats

    @property
    def scales(self):
        if not self.__scales:
            self.__scales = {}
            for variable in self.__scale_variables:
                self.__scales[variable.get_name()] = variable.get_value([])
        return self.__scales


